# Syllabus {#sec-syllabus}

{{< text_snippet wip >}}

We designed the tutorial so that by the end of it, the **learning
outcome** we hope you will have is:

-   Explain in simple terms what GitHub does and to feel confident enough 
    to navigate GitHub to work with files as well as GitHub Issues.

To break this down, we designed the tutorial into specific **learning
objectives** so that you will:

-   List and describe Git's core functionality and purpose, and how
    GitHub expands on that.
-   Explain the difference between GitHub and Git.
-   Explain how GitHub differs from services like OneDrive or Dropbox,
    and what GitHub's advantage is over them.
-   Interact with and navigate GitHub enough to create, edit, rename,
    and delete files and folders.
-   Create GitHub "Issues" to start discussions, request for some help,
    or list to-do tasks, as well as to comment on existing "Issues".
-   Explain the benefits to using Issues within the same platform as
    your files.

More concretely and more simply, during the tutorial we will:

-   Create and edit text files on GitHub.
-   Create Issues and comment on them.

## Is this course for you? {#sec-is-it-for-you}

To help manage expectations and develop the material for this course, we
make a few assumptions about *who you are* as a participant in the
course:

-   Assumptions

While we have these assumptions to help focus the content of the course,
if you have an interest in learning R but don't fit any of the above
assumptions, *you are still welcome to attend the course*! We welcome
everyone, that is until the course capacity is reached.

In addition to the assumptions, we also have a fairly focused scope for
teaching and expectations for learning. So this may also help you decide
if this course is for you.

-   List of what we will teach and won't teach
